version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - webnet

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # node + nginx 멀티스테이지 Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:

