version: '3.8'

services:
  web:
    ports:
      - "80:80"
      - "443:443"  # SSL 포트 추가
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # EC2용 nginx 설정
      - ./certbot/conf:/etc/letsencrypt  # SSL 인증서 볼륨
      - ./certbot/www:/var/www/certbot

  certbot:  # SSL 인증서 갱신용
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email tltlgn6@gmail.com --agree-tos --no-eff-email -d leecone.blog -d www.leecone.blog
    depends_on:
      - web
