version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - HOST=0.0.0.0
      - PORT=3001
      - REACT_APP_API_URL=http://localhost/api
    networks:
      - webnet

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - webnet

networks:
  webnet:
