version: '3.8'

services:
  backend:
    build: ./backend
    container_name: my-app-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-2.cxw0w0g0cyap.ap-northeast-1.rds.amazonaws.com:5432/my_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=diRlqkq99*
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - webnet
    volumes:
      - ./uploads:/app/uploads

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: my-app-web
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
