version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - webnet

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - webnet

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - webnet

networks:
  webnet:

